Allow boolean command-line options without arguments again (#92)
Currently all those arguments do not work, since they now require an argument but running a command like this: `java -jar application.jar db migrate --initOnMigrate true config.yml` results in the following exception:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
 at net.sourceforge.argparse4j.inf.Namespace.getBoolean(Namespace.java:174)
 at io.dropwizard.flyway.cli.DbMigrateCommand.run(DbMigrateCommand.java:67)
 at io.dropwizard.flyway.cli.DbCommand.run(DbCommand.java:48)
```

This PR makes it again possible to use `--initOnMigrate` without argument, but doesn't set a default value if it is not used (`null` instead)

Refs #22
Refs #23

(cherry picked from commit a954d02a77154b72187d8588859e7cdbba29688b)